version: "3.7"
services:
  hive-server:
    image: hive/server
    command: sh -c "yarn && yarn start:dev"
    ports:
        - "3000:3000"
    volumes:
        - .:/usr/src/app
      depends_on:
        - hive-postgres

  hive-postgres:
    image: postgres:12.2
    expose:
      - 5432
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: pass
        PGDATA : pass